* Can't map a key to use five or more levels :issue_resolved:

When I make a map looking like this:

#+BEGIN_SRC generic
key <AB09> { [ period, colon, periodcentered, abovedot, a, b, c, d ] };
#+END_SRC

In other words, a key with eight levels, the key doesn't work properly any more.
I can still access the first and second levels, but not the third and fourth (or
the ones beyond that).

** DONE Fix this issue when I need more than four levels
CLOSED: [2016-10-15 lø. 19:07]
- CLOSING NOTE [2016-10-15 lø. 19:07] \\
  This issue was resolved in commit r#d721475e30e0 (“Add access to
  levels 5–8”, 2016-10-08).
I won't fix this right away, since I still have convenient access to four levels
right now, and I need to (1) make better mappings for levels 3 and 4, (2) make
some "compose" key sequences of my own, and (3) get used to using this new
setup. It only makes sense to worry about levels five to eight after I have done
all of that.

* Note that depressing all shift keys on the left side of the at the keyboard introduces jamming

When I try to press all shift levels on the left side of the keyboard, the third
key won't register. I think this is because of keyboard jamming, i.e., that
these keys use the same circuits (or something) which limits how many of them
can be depressed simultaneuosly.

This is not a problem for the shift keys on the right side of the keyboard; when
I depress "Return", "BKSL" and "Shift_R" at the same time, all keypresses are
registered[fn:xev_note].

Short of using another keyboard, I can't really solve this issue. But I thought
I should make a not of it in case I get confused about it in the future.

Note that this does not induce a big limitation. It only means that I can't
conveniently access the eight level. It seems like I can still access the sixth
and seventh level, or at least most of the keys; pressing "Caps_Lock" and "LSGT"
at the same time makes a few of the "shiftable" keys on the right side of the
keyboard jam, but most of the other keys on the right side work.

[fn:xev_note] Found out by running ~xev~.

* Find a way to compile and use configurations without having to be root

My current setup means that I need sudo privileges in order to use them; I copy
the configuration files to ~/usr/share/X11/xkb/symbols/~ directory. This means
that I can’t use these configurations on computers that aren’t my own. I should
find a way to compile and use these files as a regular user. For example, maybe
there is some dot file or configuration file related to X11 that could handle
this in a neat way?

** DONE Find a way to use these files without sudo privileges
   CLOSED: [2017-06-04 sø. 19:05]

   - CLOSING NOTE [2017-06-04 sø. 19:05] \\
     I seem to have found a way to compile and use keymap files without
     sudo privileges.

     This method seems to be restricted to use /one/ custom file, since
     the `include` statements etc. in that file seems to probably use
     the files in the “standard” directory — ~/usr/share/X11/xkb/~ in my
     case.  If that’s the case, then that drawback will be workable for
     me, since I just need to put all things that depend on each other
     in the same file.

     So the method is this:

     #+BEGIN_SRC shell
     setxkbmap <mapping> -print | xkbcomp -I<custom directory> - "$DISPLAY"
     #+END_SRC

     This prints the mapping and pipes it to a compiler, and then
     finally it is passed to the display ~DISPLAY~.

     Something strange is the way the argument to ~-I~ is right next to
     it, for example (with a concrete string):

     #+BEGIN_SRC
     -I"xkb-from-usr/"
     #+END_SRC

     This weirdness is on purpose since this:

     #+BEGIN_SRC
     -I "xkb-from-usr/"
     #+END_SRC

     Seems like it doesn’t work.
** Update [2017-05-11 to.]

It seems that this link contains some good pointers:

    https://askubuntu.com/questions/875163/is-it-possible-to-use-a-custom-keyboard-layout-without-sudo-access-if-so-how

Also this one:

    https://askubuntu.com/questions/876005/what-file-is-the-setxkbmap-option-rules-meant-to-take-and-how-can-i-add-keyboa/896297#896297

** Update [2017-06-04 sø.]

I downloaded [[https://github.com/aspiers/desktop-config][Adam Spier’s]] keyboard configuration.  He has some custom
keyboard mappings.  By figuring out how he uses ~setxkbmap~ to enable
his custom mappings, I could perhaps figure out how to do the same and
in turn be able to use my own mappings without sudo priviliges.

*** Context

I found the repository in this email:

https://groups.google.com/a/listserv.bat.ru/forum/#!topic/xkb/g0Mr_IJqMKQ

* TODO find a project name

I need a project name for these configurations.  I want to name the
keymapping file after the project.
