* "AltGr" button produces newline when quickly pressed

This is due to the way I have mapped the "Return" key to "ISO_Level3_Shift", and
then this modifier back to produce the "Return" action/character when pressed.
Since "AltGr" is the original (only) character that was mapped to that
modifier, they now both emit the keycode 255 when pressed rapidly (255 is the
unused keycode that I mapped to the "Return" key).

This is not a practical issue right now, since I never press the "AltGr" key
rapidly by mistake. But it could become an issue when I am going to map "Caps
Lock" to act as another level 3 modifier when held down and pressed with other
keys.

* I should use ~setxkbmap~ instead of ~xmodmap~

I should use ~setxkbmap~ instead of ~xmodmap~ to map keys in the script, since
~xmodmap~ seems to be effectively deprecated in favour of ~setxkbmap~ in Ubuntu.
Also, apparently running a ~setxkbmap~ after having run an ~xmodmap~ command
might invalidate whatever changes the ~xmodmap~ invocation made.

* The ~<LTGT>~ key uses "repeat"

I saw through running ~xev~ that holding down the ~<LTGT>~ key lead to it being
registered again and again as a keypress, instead of just one. Since this is a
"level 5 shift" key and a compose key, I might not want to have this key
/repeat/ while depressed.

* The order matters when combining level 2 and level 3 shifts

This only happens for the ~<BKSL>~ key.

If I press and hold the ~<BKSL>~ key, and then press and hold the ~<Shift_R>~
key (while still holding down ~<BKSL>~), then I enter level 4 (level 2 and level
3 shift pressed at the same time). But if I press and hold ~<Shift_R>~ /and
then/ press and hold ~<BKSL>~, then I am still at level 2. This is not the case
for the ~<Alt_R>~ (also known as "Alt Gr") key; I can press and release this key
and ~<Shift_R>~ in any order and they still work as expected, namely that the
fourth level is accessed whenever both are depressed at the same time.

At first I thought that this had something to do with the fact that ~<Alt_R>~
was the original (and only) "level 3 shift", and that I had used ~xmodmap~ to
make ~<BKSL>~ a "level 3 shift" key. But this is /not/ an issue when it comes to
~<Caps_Lock>~ and ~<Shift_L>~; they work just as well as ~<Alt_R>~ combined with
~<Shift_R>~.

** Update

When pressing ~<BKSL>~ while running ~xev~, the "KeyPress event" registers the
keysym as "ISO_Level3_Shift", but the "KeyRelease event" registers the keysym as
"NoSymbol". This is /not/ the case for the "Caps_Lock" key; both the key press
and release events registers the keysym as "ISO_Level3_Shift".

This might be relevant to this issue.

* Locking at level 5 makes Xmonad keybindings not work

When I press the two "level 5 shift" keys together, level 5 is either locked or
unlocked (depending on the lock state). When level 5 is locked, keybindings with
the Windows/super keys don't work. Which for me means that my Xmonad kyebindings
don't work.

* "LSGT" produces "Return" on release even when pressed for long

The key "LSGT" (one of the "level 5 shift" keys) produces "Return" when held
down for a long time and then released. This is not the case for the other
"level 5 shift"  key, namely the "Return" key.

This only happens if the key is depressed and released without being used as a
chord. If it is depressed and some other key is depressed before it is released,
then a "Return" is not produced.
