* "AltGr" button produces newline when quickly pressed

This is due to the way I have mapped the "Return" key to "ISO_Level3_Shift", and
then this modifier back to produce the "Return" action/character when pressed.
Since "AltGr" is the original (only) character that was mapped to that
modifier, they now both emit the keycode 255 when pressed rapidly (255 is the
unused keycode that I mapped to the "Return" key).

This is not a practical issue right now, since I never press the "AltGr" key
rapidly by mistake. But it could become an issue when I am going to map "Caps
Lock" to act as another level 3 modifier when held down and pressed with other
keys.

* I should use ~setxkbmap~ instead of ~xmodmap~

I should use ~setxkbmap~ instead of ~xmodmap~ to map keys in the script, since
~xmodmap~ seems to be effectively deprecated in favour of ~setxkbmap~ in Ubuntu.
Also, apparently running a ~setxkbmap~ after having run an ~xmodmap~ command
might invalidate whatever changes the ~xmodmap~ invocation made.

* The ~<LTGT>~ key uses "repeat"

I saw through running ~xev~ that holding down the ~<LTGT>~ key lead to it being
registered again and again as a keypress, instead of just one. Since this is a
"level 5 shift" key and a compose key, I might not want to have this key
/repeat/ while depressed.
