Keyboard mappings for Xkb.

* Installation or setup instructions

Copy whatever xkb files you have to the directory:

#+BEGIN_SRC generic
/usr/share/X11/xkb/symbols
#+END_SRC

Remember to remove the files in this directory when you have made modifications
to one of the files in that directory:

#+BEGIN_SRC generic
/var/lib/xkb/
#+END_SRC

Set keymappings with Setxkbmap.  For example:

#+BEGIN_SRC shell
setxkbmap no_p1
#+END_SRC

If there is some file named ~no_p1~ in ~/usr/share/X11/xkb/symbols~.

Or set the ~nodeadkeys~ variant:

#+BEGIN_SRC shell
setxkbmap "no_p1(nodeadkeys)"
#+END_SRC

The quotes are necessary because of the shell.

** Other dependencies and restarting the X session

The setup that I use with ~no_p1~ depends on a script ~keyboard-setup~
to run.  Furthermore, probably because of the dependency on the [[https://github.com/alols/xcape][Xcape]]
program (if I recall correctly), the X server needs to be restarted in
case you use Setxbkmap to switch the mapping from ~no_p1~.  So if you
have the script ~keyboard-setup~ run on login to the X session, and then
run this at some point:

#+BEGIN_SRC shell
setxkbmap no
setxkbmap "no_p1(nodeadkeys)"
#+END_SRC

That mapping will not work properly.

In order to restart the X session, run:

#+BEGIN_SRC shell
sudo restart lightdm
#+END_SRC

This should take you back to the login screen.
