Keyboard mappings for Xkb.

* Installation or setup instructions

Copy whatever xkb files you have to the directory:

#+BEGIN_EXAMPLE
/usr/share/X11/xkb/symbols
#+END_EXAMPLE

Remember to remove the files in this directory when you have made modifications
to one of the files in that directory:

#+BEGIN_EXAMPLE
/var/lib/xkb/
#+END_EXAMPLE

Set keymappings with Setxkbmap.  For example:

#+BEGIN_SRC shell
setxkbmap no_p1
#+END_SRC

If there is some file named ~no_p1~ in ~/usr/share/X11/xkb/symbols~.

Or set the ~nodeadkeys~ variant:

#+BEGIN_SRC shell
setxkbmap "no_p1(nodeadkeys)"
#+END_SRC

The quotes are necessary because of the shell.

** Other dependencies and restarting the X session

The setup that I use with ~no_p1~ depends on a script ~keyboard-setup~
to run.  Furthermore, probably because of the dependency on the [[https://github.com/alols/xcape][Xcape]]
program (if I recall correctly), the X server needs to be restarted in
case you use Setxbkmap to switch the mapping from ~no_p1~.  So if you
have the script ~keyboard-setup~ run on login to the X session, and then
run this at some point:

#+BEGIN_SRC shell
setxkbmap no
setxkbmap "no_p1(nodeadkeys)"
#+END_SRC

That mapping will not work properly.

In order to restart the X session, run:

#+BEGIN_SRC shell
sudo restart lightdm
#+END_SRC

This should take you back to the login screen.

* Tools

The following are useful tools for working with Xkb.

- ~ckbcomp~: “compile a XKB keyboard description to a keymap suitable
  for loadkeys”.  Use this when the mapping won’t compile and you want
  better error messages.  Remember to use a relative path to the file if
  you want to try to compile a mapping in the current directory.
- ~setxkbmap~: “set the keyboard using the X Keyboard Extension”.
- ~man xkeyboard-config~: “XKB data description files”.  Really useful to
  find ready-made options like “swap Ctrl and Caps Lock”.
- ~xkbprint~: “print an XKB keyboard description”.  Print a PostScript
  file of a keyboard mapping.  The easiest way to use seems to be to
  print the current keyboard by using [[https://askubuntu.com/a/381393/136104][an “X display specification”:]]
  ~xkbprint :0 output.ps~.  You should be able to open the PostScript
  file in a PDF viewer.

* Files

- Keyboard mappings for the system is located in ~/usr/share/X11/xkb/symbols~.
- Compose mappings for X: ~/usr/share/X11/locale/en_US.UTF-8/Compose~.
