#!/bin/sh

# Trash compiled keymaps, which will force a recompile. In turn we avoid having
# to deal with what are effectively "stale caches" of the the keymaps.
sudo trash-put /var/lib/xkb/*

sudo cp twin-dexter /usr/share/X11/xkb/symbols/twin-dexter

# Sanity check: see if the file compiles.
ckbcomp ./twin-dexter
