#!/bin/sh

# Trash compiled keymaps, which will force a recompile. In turn we avoid having
# to deal with what are effectively "stale caches" of the the keymaps.
sudo trash-put /var/lib/xkb/*

sudo cp keyboard_1 /usr/share/X11/xkb/symbols/keyboard_1

# Sanity check: see if the file compiles.
ckbcomp ./keyboard_1
