* The source repository of XKB configurations

Apparently this is where you can find the releases of the “source” of
the XKB configuration that comes installed on Linux etc.:

https://www.freedesktop.org/wiki/Software/XKeyboardConfig/

I downloaded the repository and indeed it looks similar my XKB
configuration located at ~/usr/share/X11/xkb/~.  The directory structure
looks the same, and I opened the Norwegian (~no~) keyboard mapping file
and it looked similar to the one I have on my system.

* Example of custom configurations

Adam Spiers has a repository which among other things contains custom
keymappings, keycodes, and geometry:

https://github.com/aspiers/desktop-config/tree/master/.xkb

His keymappings (the ~symbols~ directory) might be useful to look at in
order to figure out how to structure things.

* Interesting document about Xkb

[[https://github.com/Delapouite/xkb-walkthrough][This repository]] has some nice information about Xkb.  This part in
particular struck me, since I didn’t know you could use ~|~ [fn:converted-formatting]:

#+BEGIN_QUOTE
In some case ~include~ statements can turn into behemoths, like :

#+BEGIN_SRC
include "file1(map3)+file7+file2(map1)|file1(map2)"
#+END_SRC

Two separators are involved :

- ~+~ will override an existing definition
- ~|~ will augment an existing definition
#+END_QUOTE

[fn:converted-formatting]: I’ve converted to Org formatting.

The part about the meaning of ~VoidSymbol~ was also useful, since I
should probably use that in a few places instead of ~NoSymbol~.
