#!/bin/sh

# Set keyboard layouts and options relating to keyboard layouts
#
# This program takes any number of arguments, which are used as layouts
# 1 to n (although I think you can only use up to four layouts, so you
# should probably not pass in more than four arguments).
#
# NOTE: the `-compat` option is so that level 2 latch works properly.
setxkbmap -option "" -layout "$@" \
         -compat my-complete \
         -option grp:sclk_toggle \
         -option grp_led:scroll :2 \
         -option nbsp:none -print |
             xkbcomp -I"/home/kristoffer/xkb/xkb-tree" - "$DISPLAY"
