#!/bin/sh

# Set keyboard layouts and options relating to keyboard layouts
setxkbmap -option "" -layout "twin-dexter(no-p1),twin-dexter(no-nodeadkeys)" \
         -option grp:sclk_toggle -option grp_led:scroll :2 \
         -option nbsp:none -print |
             xkbcomp -I"/home/kristoffer/xkb/xkb-tree" - "$DISPLAY"

# The following code is based on the example code in the following readme:
#     https://github.com/alols/xcape/blob/master/README.md
modifier_5="ISO_Level5_Shift"
# Return keycode = 36. Found by running `xmodmap -pke`.
xmodmap -e "keycode 36 = $modifier_5"
# Use an unused keycode for return. This value is not used by my keyboard. I
# found this out by running `xmodmap -pke`.
xmodmap -e "keycode 255 = Return"

# TODO Should this be run asynchronously? (Update: doesn't seem like it.)
xcape -e "$modifier_5=Return"
