#!/usr/bin/env perl

use strict;
use warnings;
use utf8;
use open ':std', ':encoding(UTF-8)';

my @hexes;
my @keysyms;

while (<>) {
    my @tmp = split / /;
    push @hexes, unpack ("U*", hex($tmp[0]));
    push @keysyms, $tmp[1];
}
