#!/usr/bin/env perl

use strict;
use warnings;
use utf8;
use open ':std', ':encoding(UTF-8)';
use charnames ':full';

my @symbols;
my @keysyms;

while (<>) {
    my @tmp = split / /;
    push @symbols, charnames::string_vianame("$tmp[0]");
    push @keysyms, $tmp[1];
}
