#!/usr/bin/env perl

use strict;
use warnings;
use utf8;
use open ':std', ':encoding(UTF-8)';
use charnames ':full';

my @symbols;
my @keysyms;

while (<>) {
    my @tmp = split / /;
    # The first column contains Unicode codepoints like e.g. U+2014 (EM
    # DASH).
    push @symbols, charnames::string_vianame("$tmp[0]");
    push @keysyms, $tmp[1];
}
